using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CV_Generator.Migrations
{
    /// <inheritdoc />
    public partial class AddCvTemplateCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CvTemplates",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Name = table.Column<string>(type: "text", nullable: false),
                    Description = table.Column<string>(type: "text", nullable: false),
                    TemplateType = table.Column<string>(type: "text", nullable: false),
                    Content = table.Column<string>(type: "text", nullable: false),
                    IsSystem = table.Column<bool>(type: "boolean", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: true),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CvTemplates", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CvTemplates_IsSystem",
                table: "CvTemplates",
                column: "IsSystem");

            migrationBuilder.CreateIndex(
                name: "IX_CvTemplates_UserId",
                table: "CvTemplates",
                column: "UserId");

            migrationBuilder.InsertData(
                table: "CvTemplates",
                columns: new[] { "Id", "Name", "Description", "TemplateType", "Content", "IsSystem", "UserId", "IsActive", "CreatedAt", "UpdatedAt" },
                values: new object[]
                {
                    Guid.Parse("11111111-1111-1111-1111-111111111111"),
                    "Default",
                    "Propel default CV template (LaTeX). Preamble, colors and custom macros preserved verbatim; the body is generated by the template agent and injected at the marker.",
                    "latex",
                    "% Propel default CV template (LaTeX) - injectable form.\n% Preamble, colors and custom macros are preserved verbatim; the body between\n% \\begin{document} and \\end{document} is generated by the template agent and\n% injected at the marker below.\n\\documentclass[a4paper,10pt]{article}\n\n% Packages\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage[english]{babel}\n\\usepackage{geometry}\n\\usepackage{graphicx}\n\\usepackage{xcolor}\n\\usepackage{titlesec}\n\\usepackage{enumitem}\n\\usepackage{hyperref}\n\\usepackage{fontawesome5}\n\\usepackage{array}\n\\usepackage{tabularx}\n\n% Page setup\n\\geometry{left=1cm, right=1cm, top=0.3cm, bottom=0.3cm}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0pt}\n\\setlength{\\parskip}{0pt}\n\n% Colors\n\\definecolor{darkblue}{RGB}{0, 51, 102}\n\\definecolor{lightgray}{RGB}{245, 245, 245}\n\n% Section title formatting\n\\titleformat{\\section}\n  {\\color{darkblue}\\normalsize\\bfseries}\n  {}{0em}{}[\\titlerule]\n\n\\titlespacing*{\\section}{0pt}{3pt}{2pt}\n\n% Hyperlink setup\n\\hypersetup{\n    colorlinks=true,\n    linkcolor=darkblue,\n    urlcolor=darkblue,\n    filecolor=darkblue\n}\n\n% Custom commands\n\\newcommand{\\cvitem}[2]{\n    \\textbf{#1:} #2\n}\n\n\\newcommand{\\experience}[5]{\n    \\noindent\n    \\colorbox{lightgray}{\n        \\begin{minipage}{\\dimexpr\\textwidth-2\\fboxsep}\n            \\vspace{1pt}\n            \\begin{tabularx}{\\textwidth}{@{}X r@{}}\n                {\\small\\textbf{\\color{darkblue}#1 --- #3}} & \\textcolor{darkblue}{\\small\\faCalendar\\ #2}\n            \\end{tabularx}\n            \\vspace{-2pt}\n            \\textit{\\small #4}\n            \\vspace{1pt}\n        \\end{minipage}\n    }\n    \\vspace{1pt}\n    #5\n    \\vspace{3pt}\n}\n\n\\newcommand{\\formation}[3]{\n    \\noindent\n    \\begin{tabularx}{\\textwidth}{@{}X r@{}}\n        \\textbf{#1} & \\textit{#2} \\\\\n        \\multicolumn{2}{@{}p{\\textwidth}@{}}{\\small\\itshape #3}\n    \\end{tabularx}\n    \\vspace{1pt}\n}\n\n\\begin{document}\n%=== BODY ===\n\\end{document}",
                    true,
                    null,
                    true,
                    DateTime.UtcNow,
                    DateTime.UtcNow
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CvTemplates");
        }
    }
}
