import http from 'k6/http';
import { check } from 'k6';
import { Rate } from 'k6/metrics';
import { config, SEEDED_USER } from '../config/env.js';
import { loginAs } from '../lib/auth.js';
import { jsonHeaders } from '../lib/helpers.js';

// ── Test plan ───────────────────────────────────────────────────────────────
// Goal: stress POST /api/user-content/cvprofiles. This is interesting because
// the handler does Postgres write + Kafka publish (cvprofile-created topic)
// in one request -- the same shape register.js exercises. If both register
// and cvprofile-create show similar slow p95s, Kafka producer is the
// bottleneck (not Keycloak-specific). If only register is slow, it's
// Keycloak.
//
// Each VU logs in once, then POSTs 5 unique profiles (10 VUs * 5 = 50 creates).
// Title is unique per VU+iter+runId so the test is repeatable without 409s.
//
// Run:
//   k6 run tests/performance/scenarios/cvprofiles-create.js
// ────────────────────────────────────────────────────────────────────────────

const createSuccess = new Rate('cvprofile_success_rate');

export const options = {
  vus: 10,
  iterations: 50,                                // 10 VUs * 5 each

  thresholds: {
    'http_req_failed':                       ['rate<0.05'],
    'http_req_duration{name:cvprofile-create}': ['p(95)<2000'],
    'cvprofile_success_rate':                ['rate>0.90'],
  },
};

export function setup() {
  const runId = Date.now().toString(36);
  console.log(`[cvprofile-create] run id = ${runId}`);
  return { runId };
}

export default function (data) {
  // Re-login on every iteration: k6's per-VU cookie jar does not reliably
  // persist session cookies across iterations with the shared-iterations
  // executor. The login tag keeps these requests out of the cvprofile-create threshold.
  loginAs(SEEDED_USER.email, SEEDED_USER.password);

  const dto = {
    Title:   `Perf Profile ${data.runId} v${__VU} i${__ITER}`,
    Summary: `Generated by k6 cvprofile-create scenario at ${new Date().toISOString()}.`,
  };

  const res = http.post(
    config.endpoints.cvprofiles,
    JSON.stringify(dto),
    {
      headers: jsonHeaders,
      tags: { name: 'cvprofile-create' },
    },
  );

  let body = {};
  try { body = res.json(); } catch (_) { /* ignore */ }

  const ok = check(res, {
    'status is 201':           (r) => r.status === 201,
    'returned profile id':     () => body && body.data && typeof body.data.id === 'string' && body.data.id.length > 0,
    'echoes our title':        () => body && body.data && body.data.title === dto.Title,
  });

  createSuccess.add(ok);

  if (!ok) {
    console.warn(`[cvprofile-create] VU=${__VU} iter=${__ITER} status=${res.status} body=${res.body}`);
  }
}
