name: cv

include:
  - path: ./backend/docker-compose.yml
  - path: ./ai_agents/docker-compose.yml
  - path: ./api_gateway/docker-compose.yml

services:

  # ── Frontend ─────────────────────────────────────────────────────────────────
  frontend:
    build:
      context: ./frontend
    container_name: cv-frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - cv-network

networks:
  cv-network:
    name: cv-network
    driver: bridge
