@startuml
left to right direction

actor "User" as user

rectangle Authentication {
    usecase "Register" as REG
    usecase "Login" as LOG
    usecase "Logout" as LOT
}

user --> REG
user --> LOG
user --> LOT

@enduml
