syntax = "proto3";

option csharp_namespace = "CommonProtos.Application";

message ApplicationProto {
    string id = 1;
    string candidate_id = 2;
    string cv_version_id = 3;
    string job_offer_id = 4;
    string company_name = 5;
    string position_title = 6;
    string offer_source = 7;
    string status = 8;
    string applied_at = 9;
    string updated_at = 10;
    string notes = 11;
    bool is_saved = 12;
}

message GetApplicationByIdRequest {
    string id = 1;
}

service ApplicationServiceGrpc {
    rpc GetApplicationById(GetApplicationByIdRequest) returns (ApplicationProto);
}
