"""
Orchestrator router — handles /api/v1/cv/generate and /health.
"""
import logging
from datetime import datetime
from uuid import UUID

import httpx
from fastapi import APIRouter, status

from app.core.config import settings
from app.schemas import JobRequest, WorkflowResult

logger = logging.getLogger(__name__)
router = APIRouter()


async def _post(url: str, payload: dict) -> dict:
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(url, json=payload)
        resp.raise_for_status()
        return resp.json()


async def run_cv_generation_workflow(request: JobRequest) -> WorkflowResult:
    """
    Orchestrates the 5-step CV generation workflow by calling each service in sequence.
    """
    user_id = request.user_id
    run_id = f"{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    try:
        # --- Step 1: Extract Job Requirements ---
        extractor_resp = await _post(
            f"{settings.JOB_EXTRACTOR_URL}/api/v1/extract",
            {"job_description": request.job_description, "language": "en"}
        )

        # --- Step 2: Data Matching with RAG ---
        search_resp = await _post(
            f"{settings.SEARCH_AGENT_URL}/api/v1/match",
            {"user_id": str(user_id), "job_requirements": extractor_resp}
        )

        # --- Step 3: Fill CV Template ---
        template_resp = await _post(
            f"{settings.TEMPLATE_AGENT_URL}/api/v1/render",
            {
                "cv_draft": {
                    "target_role": extractor_resp.get("job_role", ""),
                    "summary": "Autogenerated summary based on best matches.",
                    "matched_skills": search_resp.get("matched_skills", []),
                    "matched_experiences": search_resp.get("matched_experiences", []),
                    "matched_projects": search_resp.get("matched_projects", []),
                    "gap_skills": search_resp.get("gap_skills", []),
                },
                "template_id": request.template_id,
                "target_role": extractor_resp.get("job_role", ""),
            }
        )

        # --- Step 4: Validate and Optimize CV ---
        optimizer_resp = await _post(
            f"{settings.CV_OPTIMIZER_URL}/api/v1/optimize",
            {
                "job_id": run_id,
                "rendered_sections": template_resp.get("sections", []),
                "job_requirements": extractor_resp,
            }
        )

        # --- Step 5: Deliver CV ---
        # Get user email from backend
        from app.core import backend_client
        user = await backend_client.get_user(user_id)

        contact_resp = await _post(
            f"{settings.CONTACT_AGENT_URL}/api/v1/deliver",
            {
                "optimized_cv": optimizer_resp.get("optimized_cv", {}),
                "recipient_email": user.email,
            }
        )

        optimized_cv = optimizer_resp.get("optimized_cv", {})
        return WorkflowResult(
            success=True,
            message="CV generated and optimized successfully",
            ats_score=optimized_cv.get("ats_score_estimate"),
            delivery_status="sent" if contact_resp.get("success") else "failed",
            job_id=run_id,
        )

    except Exception as e:
        logger.exception("Workflow failed")
        return WorkflowResult(
            success=False,
            message=f"Workflow failed: {str(e)}"
        )


@router.post("/cv/generate", response_model=WorkflowResult, status_code=status.HTTP_200_OK)
async def generate_cv(request: JobRequest) -> WorkflowResult:
    return await run_cv_generation_workflow(request)


@router.get("/health")
async def health():
    return {"status": "ok", "service": "orchestrator"}