"""
Main Orchestrator — 5-Step AI CV Generation Workflow.
"""
import os
import logging
from datetime import datetime
from uuid import UUID

from app.core import backend_client
from app.models.job_model import JobRequest
from app.models.cv_model import CVDraft

# Agent Imports
from app.agents.job_extractor.agent import extract_job_requirements
from app.agents.job_extractor.schemas import ExtractorInput
from app.agents.search_agent.agent import match_candidate_data
from app.agents.search_agent.schemas import SearchInput
from app.agents.template_agent.agent import render_template
from app.agents.template_agent.schemas import TemplateInput
from app.agents.cv_optimizer.agent import optimize_cv
from app.agents.cv_optimizer.schemas import OptimizerInput
from app.agents.contact_agent.agent import deliver_cv
from app.agents.contact_agent.schemas import ContactInput

logger = logging.getLogger(__name__)

async def run_cv_generation_workflow(request: JobRequest) -> dict:
    """
    Orchestrates the 5-step AI CV Generation workflow.
    """
    try:
        # 0. Prep run directory for logging/artifacts
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        run_id = f"{request.user_id}_{timestamp}"
        run_dir = f"temp_runs/{run_id}"
        os.makedirs(run_dir, exist_ok=True)
        
        # 1. Fetch User Data from Backend
        user = await backend_client.get_user(request.user_id)
        
        # Save input request
        with open(f"{run_dir}/00_input_request.json", "w") as f:
            f.write(request.model_dump_json(indent=2))

        # --- Step 1: Extract Job Requirements ---
        extractor_in = ExtractorInput(job_description=request.job_description)
        job_reqs = await extract_job_requirements(extractor_in)
        
        with open(f"{run_dir}/01_extracted_requirements.json", "w") as f:
            f.write(job_reqs.model_dump_json(indent=2))

        # --- Step 2: Data Matching with RAG ---
        search_in = SearchInput(user_id=request.user_id, job_requirements=job_reqs)
        search_out = await match_candidate_data(search_in)
        
        with open(f"{run_dir}/02_rag_candidate_match.json", "w") as f:
            f.write(search_out.model_dump_json(indent=2))

        # Assemble the draft for the template agent
        cv_draft = CVDraft(
            target_role=job_reqs.job_role,
            summary="Autogenerated summary based on best matches.", # TODO: Agent 2 should probably generate this
            matched_skills=search_out.matched_skills,
            matched_experiences=search_out.matched_experiences,
            matched_projects=search_out.matched_projects,
            gap_skills=search_out.gap_skills
        )

        # --- Step 3: Fill CV Template ---
        template_in = TemplateInput(
            cv_draft=cv_draft,
            template_id=request.template_id,
            target_role=job_reqs.job_role
        )
        template_out = await render_template(template_in)
        
        with open(f"{run_dir}/03_filled_cv.json", "w") as f:
            f.write(template_out.model_dump_json(indent=2))

        # --- Step 4: Validate and Optimize CV ---
        optimizer_in = OptimizerInput(
            job_id=run_id,
            rendered_sections=template_out.sections,
            job_requirements=job_reqs
        )
        optimizer_out = await optimize_cv(optimizer_in)
        
        with open(f"{run_dir}/04_optimized_cv.json", "w") as f:
            f.write(optimizer_out.model_dump_json(indent=2))

        # --- Step 5: Deliver CV ---
        contact_in = ContactInput(
            optimized_cv=optimizer_out.optimized_cv,
            recipient_email=user.email
        )
        delivery_out = await deliver_cv(contact_in)

        return {
            "success": True,
            "message": "CV generated and optimized successfully",
            "ats_score": optimizer_out.optimized_cv.ats_score_estimate,
            "delivery_status": "sent" if delivery_out.success else "failed",
            "job_id": run_id
        }

    except Exception as e:
        logger.exception("Workflow failed")
        return {
            "success": False,
            "message": f"Workflow failed: {str(e)}"
        }
