name: bilal-vm3

networks:
  cv-network:
    name: cv-network

services:
  job-extractor:
    image: bilalmagg/job-extractor:latest
    container_name: cv-job-extractor
    networks:
      - cv-network

  contact-agent:
    image: bilalmagg/contact-agent:latest
    container_name: cv-contact-agent
    networks:
      - cv-network

  template-agent:
    image: bilalmagg/template-agent:latest
    container_name: cv-template-agent
    networks:
      - cv-network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    deploy:
      resources:
        limits:
          memory: 128M
    volumes:
      - /:/rootfs:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "7010:8080"
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
