name: bilal-vm1

networks:
  cv-network:
    name: cv-network

services:
  frontend:
    image: bilalmagg/frontend:latest
    container_name: cv-frontend
    ports:
      - "4200:80"
    environment:
      - GATEWAY_HOST=cv-api-gateway
      - GATEWAY_PORT=8080
      - FRONTEND_HOST=localhost
      - FRONTEND_PORT=4200
    networks:
      - cv-network

  api-gateway:
    image: bilalmagg/api-gateway:latest
    container_name: cv-api-gateway
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_HOST=${NOURELHOULDA_IP:-172.20.10.10}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT:-9090}
      - KEYCLOAK_EXTERNAL_HOST=${NOURELHOULDA_IP:-172.20.10.10}
      - KEYCLOAK_EXTERNAL_PORT=${KEYCLOAK_PORT:-9090}
      - KEYCLOAK_REALM=cv-realm
      - KEYCLOAK_CLIENT_ID=cv-gateway
      - KEYCLOAK_CLIENT_SECRET=change-me-in-production
      - GATEWAY_HOST=cv-api-gateway
      - GATEWAY_PORT=8080
      - USER_SERVICE_HOST=${VM2_IP:-cv-user-service}
      - USER_SERVICE_PORT=8082
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KAFKA_HOST=${NOURELHOULDA_IP:-172.20.10.10}
      - KAFKA_PORT=9092
      - FRONTEND_HOST=${VM1_IP:-localhost}
      - FRONTEND_PORT=4200
    networks:
      - cv-network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    deploy:
      resources:
        limits:
          memory: 128M
    volumes:
      - /:/rootfs:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "7010:8080"
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
