services:
  user-content-service:
    build:
      context: ../../
      dockerfile: src/user-content-service/Dockerfile
    container_name: cv-user-content-service-standalone
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8083
      - ConnectionStrings__DefaultConnection=Host=content-db;Port=5432;Database=content_db;Username=postgres;Password=postgres
      - Kafka__BootstrapServers=kafka:29092
    depends_on:
      content-db: { condition: service_healthy }
      kafka: { condition: service_started }
    networks:
      - cv-network

  content-db:
    image: pgvector/pgvector:pg16
    container_name: cv-content-db-standalone
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=content_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d content_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - cv-content-db-data:/var/lib/postgresql/data
    networks:
      - cv-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cv-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - cv-kafka-data:/var/lib/kafka/data
    networks:
      - cv-network


  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: cv-kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    networks:
      - cv-network

networks:
  cv-network:
    name: cv-network
    driver: bridge

volumes:
  cv-content-db-data:
  cv-kafka-data:

