@startuml
left to right direction
skinparam backgroundColor white
skinparam defaultFontName Helvetica

rectangle "<size:16><b>Pr. M. GHAILANI</size>\nProduct Owner" as prof

rectangle "<size:14><b>Bilal Magguilej</size>\nChef d'équipe · CI/CD · Docker" as chef

rectangle "<size:12>Mouhssine El Haouary</size>\nFullstack · Infra Cloud" as m1
rectangle "<size:12>Somia Jdia</size>\nFullstack · Infra Locale" as m2
rectangle "<size:12>Nourelhouda Ouhba</size>\nFullstack · Sécurité" as m3
rectangle "<size:12>Mohssine El Addaoui</size>\nFullstack · QA" as m4
rectangle "<size:12>Salman El-Ghrich</size>\nFullstack · Monitoring" as m5

prof --> chef
chef --> m1
chef --> m2
chef --> m3
chef --> m4
chef --> m5
@enduml
