sonar.projectKey=cv-generator-ai
sonar.projectName=CV Generator AI Agents
sonar.projectVersion=1.0

sonar.sources=app,services
sonar.test.inclusions=**/test_*.py

sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/*.pyc,**/*.pyo,**/tests/**,**/test_*.py

sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
